name: Simple Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."

  test:
    needs: build          
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."
